### ISSUE TITLE
编辑器高亮出错：Invalid regular expression

### ISSUE THREAD

**Issue by xiaofeiTM233** [bhsd-harry/codemirror-mediawiki#12]
以下代码导致编辑器高亮正则表达式报错
`[[文件:这里可有可无|任意内容]]`
其中`文件:`可为任意可识别的文件命名空间前缀，如`File:`，`file:`
即`[[File:|1]]`也导致出错，但`[[File:有没有都行|]]`正常，`[[媒体文件:有没有都行|正常]]`正常
表现为 含有此内容，编辑器即无法高亮，且此内容无法粘贴进已高亮的编辑器
![image](https://github.com/bhsd-harry/codemirror-mediawiki/assets/55832499/9fc5631b-8098-49a9-8923-5e8129194f03)
mw自带的cm编辑器正常，上周（2024年3月10日 星期日）使用时仍正常

**Comment by xiaofeiTM233** [comment]
@bhsd-harry

**Comment by bhsd-harry** [comment]
已于 v2.9.0 (606a9574b9c780bd9a784e038180e2e54e3919d6) 修复。
@xiaofeiTM233 请问是使用哪种编辑工具时加载的CodeMirror-MediaWiki？是否需要我提供临时修复措施？

**Comment by xiaofeiTM233** [comment]
> 哪种编辑工具时加载的CodeMirror-MediaWiki？

使用IPE加载的
不清楚怎么更新，直接从IPE调用出来还是2.8的（
![image](https://github.com/bhsd-harry/codemirror-mediawiki/assets/55832499/5f5bc7f7-31a4-4e23-8dc6-2a83423a1ce2)

**Comment by xiaofeiTM233** [comment]
https://testingcf.jsdelivr.net/npm/@bhsd/codemirror-mediawiki/dist/mw.min.js 获取的仍为2.8.3版本
（也就是说jsdelivr没有自动转到codemirror-mediawiki@2.9.0，不知道什么时候刷新，~~也许睡一觉就刷新了？~~
另外cdn.jsdelivr.net已自动更新至2.9.0

**Comment by bhsd-harry** [comment]
使用InPageEdit调用的情形已单独于 inpageedit/Plugins#52 修复。

**Comment by xiaofeiTM233** [comment]
今天测试时发现，2.9.0修复之后反造成原本正常高亮的页面高亮失效 @bhsd-harry 
报错仍旧
![image](https://github.com/bhsd-harry/codemirror-mediawiki/assets/55832499/3b30c07b-85de-4cb2-8fb1-129b43dd5279)
已为2.9.0版本
![image](https://github.com/bhsd-harry/codemirror-mediawiki/assets/55832499/25c8a8a1-8ce7-4067-a9df-99cf5ab12b85)

**Comment by bhsd-harry** [comment]
> 今天测试时发现，2.9.0修复之后反造成原本正常高亮的页面高亮失效

为什么加载的mw.min.js是2.8.0版本的？mw.min.js和main.min.js版本不兼容，当然会报错。

**Comment by xiaofeiTM233** [comment]
> 为什么加载的mw.min.js是2.8.0版本的？

加载的mw.min.js为2.9.0版本
![image](https://github.com/bhsd-harry/codemirror-mediawiki/assets/55832499/b759faaa-4719-4695-98c8-0b34b698bf3b)
2.8.0获取的是一个css
![image](https://github.com/bhsd-harry/codemirror-mediawiki/assets/55832499/13570d51-3917-4225-af79-f308be22522f)
似乎来自[mediawiki.min.css](https://testingcf.jsdelivr.net/npm/@bhsd/codemirror-mediawiki@2.9.0/mediawiki.min.css)的[map](https://testingcf.jsdelivr.net/sm/ce53c7c8b4ca8626eb3a7b650a9035419fed0505faeb09912467bba59dc46d1b.map)，并且会污染cm5的高亮
![image](https://github.com/bhsd-harry/codemirror-mediawiki/assets/55832499/bc6f3286-ae40-45a2-b86e-296534ffd4aa)
![image](https://github.com/bhsd-harry/codemirror-mediawiki/assets/55832499/15976e73-6681-48a3-9ea9-0851a1f6fab1)

**Comment by bhsd-harry** [comment]
@xiaofeiTM233 请提供一下网址和详细步骤，我在同样安装了CodeMirror扩展的英维使用InPageEdit或单独加载CodeMirror-MediaWiki均无法复现故障。

**Comment by bhsd-harry** [comment]
已确认故障，看起来只会在安装了CodeMirror扩展且自动清理浏览器localStorage的网站才会反复发生此类故障，否则故障只会在localStorage失效时发生一次。已于 v2.9.1 (d378b93ba292e26f5cbb4e10c53177b26bec54a5) 修复。
