### ISSUE TITLE
预览时自动滚动到编辑框位置的问题

### ISSUE THREAD

**Issue by w3jc** [bhsd-harry/codemirror-mediawiki#15]
萌百Vector皮肤，在Chrome浏览器下使用codemirror时，在view状态点击显示预览后会自动滚动到编辑框位置，而关闭codemirror时正常是保持在页面顶部位置的。此外Edge下正常，原因未知，希望排查。

**Comment by bhsd-harry** [comment]
@w3jc view状态是什么？Wikiplus吗？

**Comment by bhsd-harry** [comment]
使用Chrome浏览器无法复现。

**Comment by w3jc** [comment]
> @w3jc view状态是什么？Wikiplus吗？

抱歉说错了，是编辑状态edit，点预览后是submit，mw.config.get('wgAction')。关闭codemirror后正常，因此怀疑是codemirror的问题。

**Comment by bhsd-harry** [comment]
@w3jc 无法复现，请提供更完整的步骤。

**Comment by w3jc** [comment]
> @w3jc 无法复现，请提供更完整的步骤。


https://github.com/bhsd-harry/codemirror-mediawiki/assets/19387536/6324b0dc-0dd4-4a75-ac3b-c206407c01c7

请看视频。之前怀疑和浏览器的history.scrollRestoration有关，但是通过js调整为手动后还是会滚动。

**Comment by bhsd-harry** [comment]
@w3jc 能提供一下开启的CodeMirror功能吗？另外还可以在浏览器控制台打印一下`CodeMirror6.version`。

**Comment by w3jc** [comment]
> @w3jc 能提供一下开启的CodeMirror功能吗？另外还可以在浏览器控制台打印一下`CodeMirror6.version`。

我对开启的功能逐项关闭进行测试，最后确定造成自动滚动的是语法检查功能，CodeMirror6.version是2.9.5。
