### ISSUE TITLE
关于无法自动滚动到插入位置的问题

### ISSUE THREAD

**Issue by w3jc** [bhsd-harry/codemirror-mediawiki#18]
codemirror似乎与[textSelection](https://doc.wikimedia.org/mediawiki-core/1.34.4/js/#)有冲突？导致点击wikieditor编辑框下方的快捷插入按钮后无法自动滚动到插入位置，关闭codemirror后可以正常跳转，因此怀疑是codemirror的问题，希望检查原因。
![屏幕截图 2024-05-04 114606](https://github.com/bhsd-harry/codemirror-mediawiki/assets/19387536/f17aac7a-8838-4cbd-ba8a-4e4f5a352ef6)
![屏幕截图 2024-05-04 114636](https://github.com/bhsd-harry/codemirror-mediawiki/assets/19387536/905e61c1-f958-46bc-ad7a-194a915f91d7)

**Comment by bhsd-harry** [comment]
Wikimedia官方版本的CodeMirror 6也有[同样问题](https://en.wikipedia.org/wiki/project:sandbox?action=edit&cm6enable=1)，请先提报到[Wikimedia Phabricator](https://phabricator.wikimedia.org/)。

**Comment by bhsd-harry** [comment]
经检查发现，不同浏览器执行`document.execCommand('insertText', false, '')`时是否滚动的表现不同，无法一概而论。
