### ISSUE TITLE
语法检查<img>标签报错

### ISSUE THREAD

**Issue by w3jc** [bhsd-harry/codemirror-mediawiki#19]
WikiLint语法检查遇到<img>标签会报“孤立的"<" (tag-like)”错误，希望排查原因。
![屏幕截图 2024-05-14 182446](https://github.com/bhsd-harry/wikiparser-node/assets/19387536/8004b7ba-6e75-4b5a-b598-4cf07d89c629)

**Comment by bhsd-harry** [comment]
已于5天前的v2.12.4（ a0af1b5f268d65abcfaf5550d13386a1f607d376）修复。
请等待浏览器自动清理过期的本地存储，或手动清理`localStorage.removeItem('InPageEditMwConfig')`。

**Comment by w3jc** [comment]
清理浏览器缓存后img标签已经不报错了，但是src属性里有https会报 孤立的"https://" (lonely-http) 这个正常吗？
![屏幕截图 2024-05-17 114730](https://github.com/bhsd-harry/codemirror-mediawiki/assets/19387536/9d07a2b4-e882-4743-b2cc-984b02252e9a)

**Comment by bhsd-harry** [comment]
> 清理浏览器缓存后img标签已经不报错了，但是src属性里有https会报 孤立的"https://" (lonely-http) 这个正常吗？

这是哪个页面？控制台检查一下`CodeMirror6.version`？我无法复现。

**Comment by w3jc** [comment]
> CodeMirror6.version

2.12.6，截图这个是[用户讨论页](https://zh.moegirl.org.cn/User:It%27s_not_a_piece_of_cake)，此外还有[讨论版](https://zh.moegirl.org.cn/%E8%90%8C%E5%A8%98%E7%99%BE%E7%A7%91_talk:%E8%AE%A8%E8%AE%BA%E7%89%88/%E6%8F%90%E9%97%AE%E6%B1%82%E5%8A%A9)等有不少讨论页面都有这个报错

**Comment by bhsd-harry** [comment]
@w3jc 我还是无法复现。如果确信这个问题存在（比如尝试`safemode=1`后或是有更多用户出现相同故障），请新开一个issue并提供完整复现步骤。
