### ISSUE TITLE
语法检查lonely-http报错

### ISSUE THREAD

**Issue by w3jc** [bhsd-harry/codemirror-mediawiki#21]
在`<img>`标签中的`https://`会报lonely-http错误，例如[讨论版](https://zh.moegirl.org.cn/index.php?title=%E8%90%8C%E5%A8%98%E7%99%BE%E7%A7%91_talk:%E8%AE%A8%E8%AE%BA%E7%89%88/%E6%8F%90%E9%97%AE%E6%B1%82%E5%8A%A9&action=edit&section=1)上用户TsanconBYin的签名中。
![屏幕截图 2024-05-20 211442](https://github.com/bhsd-harry/codemirror-mediawiki/assets/19387536/0d0e75fb-f3f3-44f6-81b3-2813bf3b9638)

**Comment by bhsd-harry** [comment]
无法提供完整复现步骤时将作为`invalid`处理。

**Comment by bhsd-harry** [comment]
我好像看懂了，这个问题和 #19 本质上是同一个问题，更新到 v2.13.0 即可解决。
