### ISSUE TITLE
模板名称中含有`&`时右键跳转不正确

### ISSUE THREAD

**Issue by GuoPCinGitHub** [bhsd-harry/codemirror-mediawiki#7]
如题，如`{{VOCALOID_&_UTAU_Ranking/bricks}}`在右键点击“VOCALOID”“&”“UTAU_Ranking/bricks”会分别跳转至`[[模板:VOCALOID]]`、`[[模板:&]]`以及`[[模板:UTAU Ranking/bricks]]`。

**Comment by bhsd-harry** [comment]
这个故障在[cm6](../tree/cm6)中再次出现。
