### ISSUE TITLE
自定义tag中的wikitext无法被编辑

### ISSUE THREAD

**Issue by xiaofeiTM233** [bhsd-harry/codemirror-mediawiki#8]
开启`高亮显示匹配和未匹配的标签`后，导致mw部分自定义tag（如`<nomobile>`）中包括的wikitext无法被编辑，并且光标错位
演示

https://github.com/bhsd-harry/codemirror-mediawiki/assets/55832499/6124a693-2aa6-4300-b1d0-496d8340c65f

已测试，非单独环境特性，IPE内同样生效

**Comment by xiaofeiTM233** [comment]
另外挂一个偶发，目前未能复现，控制台没有相关报错，先不开新issue，但是怕忘，先放这（
![image](https://github.com/bhsd-harry/codemirror-mediawiki/assets/55832499/dc07e3a8-cb17-482e-a5a3-069acdb7274f)

**Comment by bhsd-harry** [comment]
> 另外挂一个偶发，目前未能复现，控制台没有相关报错，先不开新issue，但是怕忘，先放这（ !

新版本对话框大改，这个问题不再修复，除非新版本中同样可复现。
